### ISSUE TITLE
Should we add this list ?

### ISSUE THREAD

**Issue by FGRibreau** [FGRibreau/mailchecker#117]
[https://github.com/yclas/yclas/blob/master/oc/banned_domains.json](https://github.com/yclas/yclas/blob/master/oc/banned_domains.json)

What do you think? 
The sad part is that it does not only include fake emails

**Comment by benjamingr** [comment]
Yes, lots of good stuff there.

**Comment by datio** [comment]
I was about to submit a PR, after diff'ing for [unique hosts](https://gist.github.com/datio/9cec38a4e6be97e589974f52189ff4b1).
yclas is a GPL3 licensed project, is it ok to just merge the spam list into this MIT licensed project?
I've noticed attribution is always provided in the list.json. Can this file be considered derivative work?

**Comment by FGRibreau** [comment]
@datio I would happily accept this PR.

> I've noticed attribution is always provided in the list.json Can this file be considered derivative work?

I'm not sure about that but I'm not an expert in that field, what are the consequences of such affirmation?

**Comment by datio** [comment]
I was worried about the license incompatibilities between the two open source licenses.
The GPL is more "viral", in a sense that it requires all the derivative works to be released under the same viral license, whereas the MIT license doesn't pose such a requirement and is less restrictive.

For example, the [nfedyashev/valid_email2](https://github.com/nfedyashev/valid_email2/blob/master/vendor/disposable_emails.yml)'s disposable emails list which has been included in this project is under the same MIT license, so with proper attribution there shouldn't be a problem (we still miss that person's copyright.txt file from their repository though, so unless the person who submitted that PR is also the original creator of it, we're still in a grey area).

Another example is the list included from ```http://xenforo.com/community/threads/ban-temporary-email-addresses.5461/```
That list was created by collecting information shared by users in a forum. Even though the commiter probably didn't request consent from those users, his work in collecting and checking the links can be thought as original. The commiter even gave proper attribution to the source with the commented link.
As a sidenote, the resulted list can now be used by the participants of that same forum -who are mostly forum owners- as the MailChecker list.json is [available for them](https://xenforo.com/community/resources/ban-spam-emails-mailchecker.5939/) to use, so it's a win-win situation.

Disposable/spam email collections have a strong similarity to IP-to-location database dumps, such as [GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/). I believe the companies that provide and update such databases strongly enforce their copyrights, especially for their premium databases.
The list in the yclas/yclas repository is a ready to use list already. We should think of it as "proprietary" (due to the license incompatibility), as we have no consent from its copyright yet to merge it with ours.

**Comment by datio** [comment]
The merged list increases the covering to 4550 unique email hosts.
