### ISSUE TITLE
Chinese domains

### ISSUE THREAD

**Issue by egorsmkv** [FGRibreau/mailchecker#50]
Why Chinese domains in the list? This is not a temporary address.

- qq.com
- sohu.com
- 21cn.com
- yeah.net
- naver.com

And other.

**Comment by FGRibreau** [comment]
Good question, it seems they were consider like that from by the community. I will wait for "+1" to remove some :)

**Comment by trisix** [comment]
+1 for this.

IMHO, Despite some Chinese domains do have a higher chance to be used by some Chinese spammers. Yet they are also be used by lots of normal users from China. And even some people who just work there. I think for those users in China, the domain "qq.com" is just like "gmail.com" or "yahoo.com" for a U.S.  resident or some people who work in the U.S.  

On the other hand, even Google can be trust at most of time. You still can't stop spammers out there creating lots of fake accounts with Gmail. And use those accounts to spam your website. 

As I developer from Taiwan, our service get some users who keep posting spam sometimes. They use "qq.com", "hotmail.com", "gmail.com"...etc. as their email, some even use fake Facebook accounts. But we know that we can not ban those email domains and Facebook completely. Because there are more users who also use those email domains or Facebook. So we have to use some other way to deal with those problems. (FYI, we extract feature from their contents, and use something simple, like Naive Bayes spam filtering, to deal with it. Since the spam are mostly from some specific domain, they do have some patterns or keywords.)

BTW, I think "naver.com" is a Korean Domain. "Line", the popular IM app in Asia is their best known product. 

: )

**Comment by dlackty** [comment]
@FGRibreau Some domains on this list have Wikipedia pages and in general they're quite common and popular in China:

* https://en.wikipedia.org/wiki/Tencent_QQ (qq.com)
* https://en.wikipedia.org/wiki/Sohu (sohu.com)

**Comment by egorsmkv** [comment]
Thx!

**Comment by FGRibreau** [comment]
:+1: released in v3.0.8
